#!/bin/bash
#$ -N H3K9me3_Overlap_bamcompare
#$ -cwd
#$ -l h_data=8G,h_rt=2:00:00
#$ -pe shared 4

source ~/.bashrc

module load bedtools/2.30.0
module load python/3.6.8

peaks=/u/scratch/j/jadiruss/ATAC_new/enrichment/
out=/u/scratch/j/jadiruss/ATAC_new/enrichment/H3K9me3
bw105=/u/scratch/j/jadiruss/ATAC_new/E105/bw
bw145=/u/scratch/j/jadiruss/ATAC_new/E145/bw
rpt=/u/home/j/jadiruss/project-clarka/Genomes/mm39_STAR/TE
k9=/u/scratch/j/jadiruss/H3K9me3_new/bw

threads=4


source $HOME/env_python3.6.8/bin/activate

multiBigwigSummary BED-file -b $k9/E105_bamcompare_extend_RPKM_bs10.bw $k9/E135_F_bamcompare_extend_RPKM_bs10.bw \
--BED $peaks/TRIM28_E105_Muts_Female_export.bed -o $out/TRIM28_105_F.npz --outRawCounts $out/TRIM28_E105_Female_H3K9me3.bed

multiBigwigSummary BED-file -b $k9/E105_bamcompare_extend_RPKM_bs10.bw $k9/E135_F_bamcompare_extend_RPKM_bs10.bw \
--BED $peaks/TRIM28_E145_Muts_Female_export.bed -o $out/TRIM28_145_F.npz --outRawCounts $out/TRIM28_E145_Female_H3K9me3.bed

multiBigwigSummary BED-file -b $k9/E105_bamcompare_extend_RPKM_bs10.bw $k9/E135_F_bamcompare_extend_RPKM_bs10.bw \
--BED $peaks/TRIM28_E105_Muts_Male_export.bed -o $out/TRIM28_105_M.npz --outRawCounts $out/TRIM28_E105_Male_H3K9me3.bed

multiBigwigSummary BED-file -b $k9/E105_bamcompare_extend_RPKM_bs10.bw $k9/E135_M_bamcompare_extend_RPKM_bs10.bw \
--BED $peaks/TRIM28_E145_Muts_Male_export.bed -o $out/TRIM28_145_M.npz --outRawCounts $out/TRIM28_E145_Male_H3K9me3.bed
